# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghc < Formula
  desc ""
  homepage "https://zeiss.github.io/ghc/"
  version "0.1.1"
  license "APACHE-2.0"

  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/ZEISS/ghc/releases/download/v0.1.1/ghc_0.1.1_darwin_amd64.tar.gz"
      sha256 "0b5492615cd7c7cc83c7d9e8befffdbcd9c7be27e6b3c416c1ac8234297e4d02"

      def install
        bin.install "ghc"
      end
    end
    on_arm do
      url "https://github.com/ZEISS/ghc/releases/download/v0.1.1/ghc_0.1.1_darwin_arm64.tar.gz"
      sha256 "f62b5a1b3768223675c4e565db4e07d41bf74741a37e38a34c81f851415605a8"

      def install
        bin.install "ghc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZEISS/ghc/releases/download/v0.1.1/ghc_0.1.1_linux_amd64.tar.gz"
        sha256 "bfe9fae0ed612d56731a1d826c2114c4aefff14885561606967270052c5dd4e3"

        def install
          bin.install "ghc"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ZEISS/ghc/releases/download/v0.1.1/ghc_0.1.1_linux_arm.tar.gz"
        sha256 "ad8beb8d35582a8cc69c0b8da665ae78b092de99337584b86132ae25361fc745"

        def install
          bin.install "ghc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZEISS/ghc/releases/download/v0.1.1/ghc_0.1.1_linux_arm64.tar.gz"
        sha256 "71b1abc3d487843cbeeb178c600d20e1bee3556b628e31db47887d0b9d3289cc"

        def install
          bin.install "ghc"
        end
      end
    end
  end
end
