# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghc < Formula
  desc ""
  homepage "https://zeiss.github.io/ghc/"
  version "0.1.0"
  license "APACHE-2.0"

  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/ZEISS/ghc/releases/download/v0.1.0/ghc_0.1.0_darwin_amd64.tar.gz"
      sha256 "6bfd2de090e8b7de8fa25b35e0a2297d7cbc39495ad70354f1aedbe728ee4cfd"

      def install
        bin.install "ghc"
      end
    end
    on_arm do
      url "https://github.com/ZEISS/ghc/releases/download/v0.1.0/ghc_0.1.0_darwin_arm64.tar.gz"
      sha256 "cca35197123d95639253f86bbf134f07bbdae265b91dee11217f7c250286896c"

      def install
        bin.install "ghc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZEISS/ghc/releases/download/v0.1.0/ghc_0.1.0_linux_amd64.tar.gz"
        sha256 "3e23be0e03251d1002be59287d56f05ce04861574290f8979e56348e2b56bbf9"

        def install
          bin.install "ghc"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ZEISS/ghc/releases/download/v0.1.0/ghc_0.1.0_linux_arm.tar.gz"
        sha256 "8bf25ef9848ff1fd4da0d79562fec874ce62e47dcab17eaaed1efe4cadc44367"

        def install
          bin.install "ghc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZEISS/ghc/releases/download/v0.1.0/ghc_0.1.0_linux_arm64.tar.gz"
        sha256 "a37a01f97a0a8a0ef2f8e92cfaf0a13b3ea171cddc99aaab5b9e157ee452b2f8"

        def install
          bin.install "ghc"
        end
      end
    end
  end
end
